### ISSUE TITLE
用户密码无法重置bug

### ISSUE THREAD

**Issue by EllusionLee** [Lucianhz/xp-iOS#6]
测试一下开发平台  账户: test00的密码现在是否是 123456  .

**Comment by EllusionLee** [comment]
我这边主要没有可以用于测试的设备,麻烦你那边测试一下 @sxluohaibo

**Comment by sxluohaibo** [comment]
我试下

**Comment by sxluohaibo** [comment]
密码不是123456

**Comment by EllusionLee** [comment]
那应该就是还不行. 我再看下吧

**Comment by caijiang** [comment]
@EllusionLee 现在重置密码报错。

**Comment by sxluohaibo** [comment]
@caijiang 这是服务端问题还是前端要改？

**Comment by caijiang** [comment]
这是服务端问题； 因为没有开发版的安卓 所以让你协助测试一下而已。
